[profile.default]
src = 'contracts'
out = 'out/foundry'
libs = ["node_modules", "lib"]
test = 'tests'
cache_path  = 'out/cache_forge'
broadcast = 'out/foundry-broadcast'
fs_permissions = [{ access = "write", path = "./.env"}]
allow_paths= ['../../node_modules']
