services:
  - type: web
    name: composooor-api
    plan: free
    env: node
    repo: https://github.com/kairos-loan/composooor.git
    branch: main
    region: frankfurt
    buildCommand: yarn && api build
    startCommand: yarn api start:prod
    numInstances: 1
    healthCheckPath: /api/heartbeat
    autoDeploy: true

  - type: web
    name: composooor-app
    env: static
    repo: https://github.com/kairos-loan/composooor.git
    branch: main
    # buildFilter:
    #   paths:
    #     - src/**/*.js
    #   ignoredPaths:
    #     - src/**/*.test.js
    staticPublishPath: ./dist
    autoDeploy: true
