/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export const ContractAddresses_31337 = {
  BuyNowPayLater: "0x42Cc87749B4031c53181692c537622e5c3b7d061",
  SmartContractWallet: "0x2B2f78c5BF6D9C12Ee1225D5F374aa91204580c3",
};
