/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

export const ContractAddresses_31337 = {
  BuyNowPayLater: "0x31d2e3fe0Aa291CC7f29d59C0FF1EdBB345Ddfb7",
  SmartContractWallet: "0x1a8366cEa6E652f091FFf3463459BE5982b13a55",
};
