/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ContractAddresses_31337 } from "./31337";
export type ContractAddressesKey = keyof typeof ContractAddresses;
export const ContractAddresses = {
  31337: ContractAddresses_31337,
};
